version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
    volumes:
    - ./scripts:/docker-entrypoint-initdb.d
    ports:
    - 3307:3306